[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[keyboard]
bindings = [
	{ key = "Space", mods = "Control", mode = "~Alt", action = "ToggleViMode" },
	{ key = "Escape", mode = "Vi", action = "ToggleViMode" },
	{ key = "Y", mode = "Vi", action = "Copy" },
	{ key = "Y", mode = "Vi", action = "ClearSelection" },
	{ key = "Y", mode = "Vi", action = "ToggleViMode" },
]

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
